# fly.toml app configuration file generated for sigalit3 on 2025-08-07T07:46:22+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'sigalit3'
primary_region = 'lhr'

[build]

[env]
  NODE_ENV = "production"
  PORT = "4000"

[http_service]
  internal_port = 4000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[http_service.checks]]
  grace_period = "10s"
  interval = "30s"
  method = "GET"
  timeout = "5s"
  path = "/health"

[mounts]
  source = "sigalit_data"
  destination = "/app/data"

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
