# Fly.io Configuration for Sigalit
app = "sigalit-scheduling"
primary_region = "fra"  # Frankfurt (closer to Israel)
kill_signal = "SIGINT"
kill_timeout = 5

[build]

[env]
  NODE_ENV = "production"
  PORT = "4000"

[http_service]
  internal_port = 4000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

  [http_service.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20

[[http_service.checks]]
  grace_period = "10s"
  interval = "30s"
  method = "GET"
  timeout = "5s"
  path = "/"

[processes]
  app = "npm start"

[[vm]]
  size = "shared-cpu-1x"
  memory = "512MB"

# PostgreSQL addon will be configured via fly postgres
[postgres]