# Fly.io Launch Configuration
# This file helps Fly.io properly detect and configure the Node.js application

[build]
  dockerfile = "Dockerfile"

[env]
  NODE_ENV = "production"
  PORT = "4000"

[processes]
  app = "node app.js"

[checks]
  [checks.app]
    port = 4000
    type = "http"
    interval = "30s"
    timeout = "5s"
    grace_period = "10s"
    method = "GET"
    path = "/health"
